-- File: create_external_tables.hql

USE journey;

CREATE EXTERNAL TABLE IF NOT EXISTS product
(PRODUCT_ID INT, MANUFACTURER INT, DEPARTMENT STRING, BRAND STRING, COMMODITY_DESC STRING, SUB_COMMODITY_DESC STRING, CURR_SIZE_OF_PRODUCT STRING)
COMMENT 'journey product list cleaned'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
tblproperties ("skip.header.line.count"="1");

LOAD DATA LOCAL INPATH 'product.csv' OVERWRITE INTO TABLE product;